### ISSUE TITLE
Testing roadmap

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/functional-testing-2#14]
This ticket is an attempt to summarise the cross-repo stuff that's been happening with testing in PINTS.

See also [this project](https://github.com/orgs/pints-team/projects/2)

There are different aspects to testing PINTS.

- [x] **Unit tests** are implemented for each bit of the code. For simple methods, these test the full functionality (is the result returned the correct one). For complex ones --- i.e. the central algorithms in samplers and optimisers --- these mostly test the API (does the result have the right shape, are errors thrown for incorrect input). Simpler parts of sampler & optimiser classes _should_ still be tested, e.g. does get_x() return the value passed in with set_x(). 
  - [x] PINTS has **100% unit test coverage** and PRs can only be merged if they maintain this ratio.
  - [ ] It may be good to add **value-based unit tests** for the optimisers/samplers: these would seed, run, and simply check that the result is the same as the last time it was run (whether or not the result is "correct"): https://github.com/pints-team/pints/issues/1260
- [ ] **Method merge tests** are notebooks, [stored in a separate repository](https://github.com/pints-team/method-merge-tests), that show how well new notebooks perform on toy problems.
  - [ ] [This ticket](https://github.com/pints-team/method-merge-tests/issues/1) shows who is (or was!) assigned to each method. Feel free to add yourself and add another test!
  - [ ] Once you've picked a test, please also open an issue [here](https://github.com/pints-team/method-merge-tests/issues), or assign yourself to an existing issue for this test
- [ ] A **PR Template** will be created that reminds people to have a merge test notebook ready when they introduce a new method: https://github.com/pints-team/pints/issues/1276
- [ ] Based on the method merge tests, we will create **functional tests** for each method: https://github.com/pints-team/pints/issues/1294
- [ ] The results of functional tests will be monitored with **changepoint detection** algorithms: https://github.com/pints-team/functional-testing-2 and https://github.com/pints-team/change-point-testing/issues/38 and https://github.com/pints-team/functional-testing-2/issues/13

### Old stuff, probably best deleted
- [ ] First attempt at functional and change-point testing https://github.com/pints-team/change-point-testing
- [ ] Single page draft https://github.com/pints-team/functional-testing-paper
